ERROR - 2022-11-09 05:54:19 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\miProyecto\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717, Array)
#1 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1717): mail('oscar.cid@upla....', '=?UTF-8?Q?Email...', 'Testing the ema...', 'Date: Wed, 9 No...', '-f oscar.cid@up...')
#2 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(76): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#6 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-11-09 05:54:19 --> Call to undefined method CodeIgniter\Email\Email::errors()
in APPPATH\Controllers\Usuario.php on line 79.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-09 05:55:50 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\miProyecto\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717, Array)
#1 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1717): mail('oscar.cid@upla....', '=?UTF-8?Q?Email...', 'Testing the ema...', 'Date: Wed, 9 No...', '-f oscar.cid@up...')
#2 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(76): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#6 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-11-09 06:01:07 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\miProyecto\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717, Array)
#1 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1717): mail('oscar.cid@upla....', '=?UTF-8?Q?Email...', 'Testing the ema...', 'Date: Wed, 9 No...', '-f oscar.cid@up...')
#2 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(77): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#6 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-11-09 06:03:26 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\miProyecto\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717, Array)
#1 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1717): mail('oscar.cid@upla....', '=?UTF-8?Q?Email...', 'Testing the ema...', 'Date: Wed, 9 No...', '-f clasemultime...')
#2 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(77): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#6 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-11-09 06:06:08 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\miProyecto\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717, Array)
#1 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1717): mail('oscar.cid@upla....', '=?UTF-8?Q?Email...', 'Testing the ema...', 'Date: Wed, 9 No...', '-f clasemultime...')
#2 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(77): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#6 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-11-09 06:11:02 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\miProyecto\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717, Array)
#1 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1717): mail('oscar.cid@upla....', '=?UTF-8?Q?Email...', 'Testing the ema...', 'Date: Wed, 9 No...', '-f clasemultime...')
#2 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(78): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#6 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-11-09 06:14:25 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\miProyecto\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717, Array)
#1 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1717): mail('oscar.cid@upla....', '=?UTF-8?Q?Email...', 'This is a multi...', 'Date: Wed, 9 No...', '-f clasemultime...')
#2 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(79): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#6 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-11-09 06:23:38 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\miProyecto\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717, Array)
#1 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1717): mail('oscar.cid@upla....', '=?UTF-8?Q?Email...', 'This is a multi...', 'Date: Wed, 9 No...', '-f clasemultime...')
#2 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(80): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#6 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-11-09 06:28:17 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\miProyecto\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717, Array)
#1 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1717): mail('oscar.cid@upla....', '=?UTF-8?Q?Email...', 'This is a multi...', 'Date: Wed, 9 No...', '-f clasemultime...')
#2 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(81): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#6 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-11-09 06:29:50 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\miProyecto\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717, Array)
#1 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1717): mail('oscar.cid@upla....', '=?UTF-8?Q?Email...', 'This is a multi...', 'Date: Wed, 9 No...', '-f oscar.cid@up...')
#2 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(81): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#6 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-11-09 06:31:36 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\miProyecto\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717, Array)
#1 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1717): mail('oscar.cid@upla....', '=?UTF-8?Q?Email...', 'This is a multi...', 'Date: Wed, 9 No...', '-f clasemultime...')
#2 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(81): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#6 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-11-09 06:33:03 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\miProyecto\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717, Array)
#1 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1717): mail('oscar.cid@upla....', '=?UTF-8?Q?Email...', 'This is a multi...', 'Date: Wed, 9 No...', '-f clasemultime...')
#2 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(81): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#6 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-11-09 06:46:36 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\miProyecto\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717, Array)
#1 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1717): mail('oscar.cid@upla....', '=?UTF-8?Q?Email...', 'This is a multi...', 'Date: Wed, 9 No...', '-f clasemultime...')
#2 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\miProyecto\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\miProyecto\app\Controllers\Usuario.php(81): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(904): App\Controllers\Usuario->insertaNuevoUsuario()
#6 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\miProyecto\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\miProyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
